### ISSUE TITLE
Unable to establish Mycroft Messagebus Connection on Mycroft's side

### ISSUE THREAD

**Issue by modern-online** [MycroftAI/mycroft-messagebus-client#22]
On a virtual machine running Ubuntu 20.04 (VirtualBox, and also Parallels Desktop), after installing the latest messagebus-client Mycroft hangs on "Establishing Mycroft Messagebus Connection". 

I tried installing from source yet nothing seems to fix the issue. Even removing the messagebus module leaves Mycroft hanging unless I do a full reinstall. I also tried opening the socket port in firewall to no avail. 

I checked the bus.log and it logs "message bus service started" but then has: 101 GET /core (127.0.0.1)

[Update] I found an error in the enclosure.log: 
error from callback <bound method MessageBusClient.on_message>: on_message takes 2 positional arguments but 3 were given
also "on_open takes 1 but 2 were given"

**Comment by forslund** [comment]
Hi

There is a mycroft-core PR for updating to the latest mycroft-messagebus-client, https://github.com/MycroftAI/mycroft-core/pull/2879

Is this what you was trying?

And is the gui connection that's hanging or is it core itself?

Also thanks for pointing this out. it seems that PR misses updating the gui bus, will point this out.

**Comment by modern-online** [comment]
I think it's the GUI that breaks but then that somehow makes everything else hang because Mycroft is completely not responsive. Actually, if I restart Mycroft services I can see the errors from the bus log finally coming through to the GUI before it hangs again. So I guess the bus just freezes everything.

**Comment by forslund** [comment]
Mycroft-core will not work with the 0.9.2 version of the messagebus-client until https://github.com/MycroftAI/mycroft-core/pull/2879 is updated and merged. the Dev branch of core will likely work a bit better but the gui will still fail I think.

**Comment by modern-online** [comment]
I see, is the 0.9.1 the latest supported version?

**Comment by forslund** [comment]
The version in mycroft-core has been updated to v0.9.4 so this should work now. Closing the issue, if you still has problems feel free to reopen this issue.
