### ISSUE TITLE
message.response should use message.reply internally

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-messagebus-client#29]
to account for proper message routing https://github.com/JarbasHiveMind/HiveMind-core/wiki/Mycroft-Messages + https://github.com/MycroftAI/mycroft-core/pull/2461

**Comment by forslund** [comment]
Indeed, this seem to have been missed when breaking it out. Will fix.

**Comment by JarbasAl** [comment]
sorry @forslund i'm too fast :P
