### ISSUE TITLE
0.8.3 fails to install from pip

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-messagebus-client#9]
0.8.2 and bellow work

```
Collecting mycroft-messagebus-client
  Downloading mycroft-messagebus-client-0.8.3.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7h7o48jj/mycroft-messagebus-client/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7h7o48jj/mycroft-messagebus-client/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-88a2zixk
         cwd: /tmp/pip-install-7h7o48jj/mycroft-messagebus-client/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7h7o48jj/mycroft-messagebus-client/setup.py", line 42, in <module>
        install_requires=required('requirements.txt'),
      File "/tmp/pip-install-7h7o48jj/mycroft-messagebus-client/setup.py", line 32, in required
        with open(os.path.join(base_dir, requirements_file), 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-7h7o48jj/mycroft-messagebus-client/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.1; however, version 20.2.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.

```

**Comment by JarbasAl** [comment]
seems related to https://github.com/MycroftAI/mycroft-messagebus-client/commit/40f8303f276e3a19e1e5a2b2e58169f26edd3a5c

you are not passing `include_package_data=True` in setup.py

**Comment by krisgesling** [comment]
Really strange that this works in v0.8.2 which included that commit

**Comment by krisgesling** [comment]
Potentially the issue is that we added the `MANIFEST.in` but it doesn't include requirements.txt

My read of [the documentation](https://docs.python.org/3.6/distutils/sourcedist.html#specifying-the-files-to-distribute) is that this file will be auto-generated if it doesn't exist.

This still doesn't explain why the v0.8.2 release works...

I'm also failing to replicate the issue with 0.8.3 when installing from newly generated local packages. It definitely is not working installing from PyPI.

**Comment by krisgesling** [comment]
This [SO thread](https://stackoverflow.com/questions/7522250/how-to-include-package-data-with-setuptools-distutils#14159430) suggests it may be beneficial to do both `package_data` and include it via `MANIFEST.in`

**Comment by krisgesling** [comment]
PyPI is updated and it seems to be installing without issue now.
